
name: Deployment LP to Prod

on:
  push:
    branches: master
jobs:

  Deployment:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Prod
        if: github.ref == 'refs/heads/master'
        env:
          PRIVATE_KEY: ${{ secrets.Life_LP_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.Life_LP_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.Life_LP_HOSTNAME }} '
            cd /var/www/html/Life-LP &&
            sudo git pull origin master '
 

            

      
  
